# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZWiP98TUzpd1UawzhvJXcmOOZHaapAV
"""

# Task 1 : Build a Calculator CLI App

def addition(num1, num2):
  return num1 + num2
def sub(num1, num2):
  return num1 - num2
def multiply(num1, num2):
  return num1 * num2
def division(num1 , num2):
  return num1/num2

while True:
  k= int(input("Enter 1 to continue and 0 to exit"))
  if k== 0:
    break
  n=int(input("Enter the first number "))
  n2= int(input("Enter the second number "))
  c= input("Enter '+' for addition '-' for substraction '*' for multiplication and '/' for division ")
  if( c== '+'):
    print(addition(n,n2))
  elif(c== '-'):
    print(sub(n, n2))
  elif(c== '*'):
    print(multiply(n,n2))
  elif(c== '/'):
    print(division(n,n2))
  else:
    print("Wrong Choice ")

'''Interview Questions

1. What is normalization?
Answer: Normalization is a process in Database Management Systems (DBMS)
 used to organize data
 efficiently by eliminating redundancy and ensuring data integrity.

2. Primary Key vs Foreign Key

Answer:Primary Key uniquely identifies each row in a table.

Foreign Key is a field in one table that refers to the Primary Key in another table.

3. What are Constraints?
Answer: Constraints are rules applied to table columns to enforce data integrity, e.g., NOT NULL, UNIQUE, CHECK, PRIMARY KEY, FOREIGN KEY.

4. What is a Surrogate Key?
Answer : A Surrogate Key is an artificial key, usually an auto-incremented number, used as a unique identifier instead of natural keys.

5. How do you avoid Data Redundancy?
Answer: By applying Normalization and using foreign keys to separate data into related tables.

6. What is an ER Diagram?
Answer: An Entity-Relationship (ER) Diagram visually represents the entities, their attributes, and relationships in a database.

7. Types of Relationships in DBMS

Answer: One-to-One (1:1)

One-to-Many (1:N)

Many-to-Many (M:N)

8. Purpose of AUTO_INCREMENT
Answer : AUTO_INCREMENT automatically generates a unique value for a column (usually a primary key) when a new row is inserted.

9. Default Storage in MySQL
Answer: The default storage engine is InnoDB, which supports transactions and foreign keys.

10. What is a Composite Key?
Answer : A Composite Key is a combination of two or more columns that together uniquely identify a row in a table.


'''

